spring:
  application:
    name=ForoHub:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost/foro_hub
    username: root

server:
  error:
    include-stacktrace: never

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    secret: ${JWT_SECRET:123456}
