spring:
  application:
    name=ForoHub:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost/foro_hub
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true