spring:
  application:
    name=ForoHub:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  error:
    include-stacktrace: never

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    secret: ${JWT_SECRET:123456}
